### ISSUE TITLE
Error Loading Model ... Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by quirkyjoe** [skier233/nsfw_ai_model_server#8]
I am seeing the following when trying to launch (using start.p1s on Windows):
![image](https://github.com/user-attachments/assets/54e0b27a-3d9d-4d55-a0f7-b5970351cac8)

Any guidance on what I can adjust/try to resolve this?

**Comment by skier233** [comment]
What graphics card are you using?

**Comment by quirkyjoe** [comment]
I'm using a 1080TI (OC).
Perhaps too old?
If so, how do I use CPU, even if it is much slower?

**Comment by skier233** [comment]
I would expect that should work still. Can you try activating the conda environment with “conda activate ai_model_server” and then run “python diagnose_gpu.py” inside the ai server folder.

**Comment by quirkyjoe** [comment]
`(ai_model_server) PS H:\XX\nsfw_ai_model_server> python diagnose_gpu.py
False
Traceback (most recent call last):
  File "H:\XX\nsfw_ai_model_server\diagnose_gpu.py", line 4, in <module>
    print(torch.cuda.current_device())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\anaconda3\envs\ai_model_server\Lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\XX\anaconda3\envs\ai_model_server\Lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled`

**Comment by skier233** [comment]
I’d try updating your gpu driver if there’s an available update and then after remove the conda environment with:
conda remove --name ai_model_server --all
and then run install.ps1 again.

**Comment by quirkyjoe** [comment]
I performed the described steps, and upgraded my driver (to 560.81).
Running nvidia-smi shows a CUDA version of 12.6.
Unfortunately, after using the install script again, I have the same error.

**Comment by skier233** [comment]
were there any errors or warnings during the install with install.ps1?

**Comment by quirkyjoe** [comment]
No, it completes successfully, then tries to start, then fails with the error above.

**Comment by skier233** [comment]
Can you try these commands and show the output:
conda activate ai_model_server
pip uninstall torchvision
pip uninstall torch
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia

**Comment by quirkyjoe** [comment]
This resolved the issue.
The server appears to be running correctly.
Thank you!

Outputs:
```
PS H:\XXX\nsfw_ai_model_server> conda activate ai_model_server
(ai_model_server) PS H:\XXX\nsfw_ai_model_server> pip uninstall torchvision
Found existing installation: torchvision 0.18.1a0
Uninstalling torchvision-0.18.1a0:
  Would remove:
    c:\users\XXX\anaconda3\envs\ai_model_server\lib\site-packages\torchvision-0.18.1a0.dist-info\*
    c:\users\XXX\anaconda3\envs\ai_model_server\lib\site-packages\torchvision\*
Proceed (Y/n)? y
  Successfully uninstalled torchvision-0.18.1a0
(ai_model_server) PS H:\XXX\nsfw_ai_model_server> pip uninstall torch
Found existing installation: torch 2.3.1
Uninstalling torch-2.3.1:
  Would remove:
    c:\users\XXX\anaconda3\envs\ai_model_server\lib\site-packages\functorch
    c:\users\XXX\anaconda3\envs\ai_model_server\lib\site-packages\torch
    c:\users\XXX\anaconda3\envs\ai_model_server\lib\site-packages\torch-2.3.1-py3.11.egg-info
    c:\users\XXX\anaconda3\envs\ai_model_server\lib\site-packages\torchgen
    c:\users\XXX\anaconda3\envs\ai_model_server\scripts\convert-caffe2-to-onnx-script.py
    c:\users\XXX\anaconda3\envs\ai_model_server\scripts\convert-caffe2-to-onnx.exe
    c:\users\XXX\anaconda3\envs\ai_model_server\scripts\convert-onnx-to-caffe2-script.py
    c:\users\XXX\anaconda3\envs\ai_model_server\scripts\convert-onnx-to-caffe2.exe
    c:\users\XXX\anaconda3\envs\ai_model_server\scripts\torchrun-script.py
    c:\users\XXX\anaconda3\envs\ai_model_server\scripts\torchrun.exe
Proceed (Y/n)? y
  Successfully uninstalled torch-2.3.1
(ai_model_server) PS H:\XXX\nsfw_ai_model_server> conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
Retrieving notices: ...working... done
Channels:
 - pytorch
 - nvidia
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\XXX\anaconda3\envs\ai_model_server

  added / updated specs:
    - pytorch
    - pytorch-cuda=12.1
    - torchaudio
    - torchvision

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    brotli-python-1.0.9        |  py311hd77b12b_8         347 KB
    certifi-2024.7.4           |  py311haa95532_0         160 KB
    charset-normalizer-3.3.2   |     pyhd3eb1b0_0          44 KB
    idna-3.7                   |  py311haa95532_0         133 KB
    libjpeg-turbo-2.0.0        |       h196d8e1_0         618 KB
    mkl-service-2.4.0          |  py311h2bbff1b_1          44 KB
    mkl_fft-1.3.8              |  py311h2bbff1b_0         179 KB
    mkl_random-1.2.4           |  py311h59b6b97_0         228 KB
    numpy-1.26.4               |  py311hdab7c0b_0          11 KB
    numpy-base-1.26.4          |  py311hd01c5d8_0         9.1 MB
    pysocks-1.7.1              |  py311haa95532_0          36 KB
    pytorch-2.4.0              |py3.11_cuda12.1_cudnn9_0        1.21 GB  pytorch
    pytorch-mutex-1.0          |             cuda           3 KB  pytorch
    requests-2.32.3            |  py311haa95532_0         128 KB
    torchaudio-2.4.0           |      py311_cu121         7.2 MB  pytorch
    torchvision-0.19.0         |      py311_cu121         7.9 MB  pytorch
    urllib3-2.2.2              |  py311haa95532_0         228 KB
    win_inet_pton-1.1.0        |  py311haa95532_0          10 KB
    ------------------------------------------------------------
                                           Total:        1.23 GB

The following NEW packages will be INSTALLED:

  brotli-python      pkgs/main/win-64::brotli-python-1.0.9-py311hd77b12b_8
  certifi            pkgs/main/win-64::certifi-2024.7.4-py311haa95532_0
  charset-normalizer pkgs/main/noarch::charset-normalizer-3.3.2-pyhd3eb1b0_0
  idna               pkgs/main/win-64::idna-3.7-py311haa95532_0
  libjpeg-turbo      pkgs/main/win-64::libjpeg-turbo-2.0.0-h196d8e1_0
  pysocks            pkgs/main/win-64::pysocks-1.7.1-py311haa95532_0
  requests           pkgs/main/win-64::requests-2.32.3-py311haa95532_0
  tbb                pkgs/main/win-64::tbb-2021.8.0-h59b6b97_0
  torchaudio         pytorch/win-64::torchaudio-2.4.0-py311_cu121
  urllib3            pkgs/main/win-64::urllib3-2.2.2-py311haa95532_0
  win_inet_pton      pkgs/main/win-64::win_inet_pton-1.1.0-py311haa95532_0

The following packages will be UPDATED:

  intel-openmp                       2021.4.0-haa95532_3556 --> 2023.1.0-h59b6b97_46320
  mkl                                 2021.4.0-haa95532_640 --> 2023.1.0-h6b88ed4_46358
  mkl-service                         2.4.0-py311h2bbff1b_0 --> 2.4.0-py311h2bbff1b_1
  mkl_fft                             1.3.1-py311h743a336_0 --> 1.3.8-py311h2bbff1b_0
  mkl_random                          1.2.2-py311heda8569_0 --> 1.2.4-py311h59b6b97_0
  numpy                              1.24.3-py311ha6a8073_0 --> 1.26.4-py311hdab7c0b_0
  numpy-base                         1.24.3-py311h877bb12_0 --> 1.26.4-py311hd01c5d8_0
  pytorch                                2.3.1-py3.11_cpu_0 --> 2.4.0-py3.11_cuda12.1_cudnn9_0
  pytorch-mutex                                     1.0-cpu --> 1.0-cuda
  torchvision        pkgs/main::torchvision-0.18.1-cpu_py3~ --> pytorch::torchvision-0.19.0-py311_cu121


Proceed ([y]/n)? y

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by skier233** [comment]
I’m a little surprised but glad that fixed it. Something must’ve got hung up in the install process or something. Glad it’s working now!
